# Generated by Django 3.1.3 on 2020-11-30 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('idKlient', models.AutoField(primary_key=True, serialize=False)),
                ('Imie', models.CharField(max_length=50)),
                ('Nazwisko', models.CharField(max_length=50)),
                ('Wiek', models.IntegerField()),
                ('NrTel', models.IntegerField()),
                ('Email', models.CharField(max_length=200)),
                ('RodzajUlgi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Przystanek',
            fields=[
                ('idPrzysanek', models.AutoField(primary_key=True, serialize=False)),
                ('Nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trasa',
            fields=[
                ('idTrasa', models.AutoField(primary_key=True, serialize=False)),
                ('czas', models.DateTimeField()),
                ('idPrzystanek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.przystanek')),
            ],
        ),
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('idKurs', models.AutoField(primary_key=True, serialize=False)),
                ('Przewoniznik', models.CharField(max_length=45)),
                ('ilosc_miejsc', models.BigIntegerField()),
                ('Cena', models.FloatField()),
                ('idTrasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.trasa')),
            ],
        ),
        migrations.CreateModel(
            name='KupioneBilety',
            fields=[
                ('idBilet', models.AutoField(primary_key=True, serialize=False)),
                ('idKlient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.klient')),
                ('idKurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.kurs')),
            ],
        ),
    ]
